# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_dist_euclidean <- function(inMat) {
    .Call(`_macam_cpp_dist_euclidean`, inMat)
}

cpp_dist_maxnorm <- function(inMat) {
    .Call(`_macam_cpp_dist_maxnorm`, inMat)
}

cpp_quantile <- function(inVec, q) {
    .Call(`_macam_cpp_quantile`, inVec, q)
}

cpp_greater <- function(inMat, inThreshold) {
    .Call(`_macam_cpp_greater`, inMat, inThreshold)
}

cpp_distOneZero <- function(inMat, inMethod, s = 0.875) {
    .Call(`_macam_cpp_distOneZero`, inMat, inMethod, s)
}

cpp_twinSurrogate <- function(original_e, dim, num_iter, s = 0.875, surrogate_option = "random", initial_point = "same_season", distance_method = "norm", point_per_year = 24L, s_update = "on", n_twin_threshold = 10L, output_message = FALSE) {
    .Call(`_macam_cpp_twinSurrogate`, original_e, dim, num_iter, s, surrogate_option, initial_point, distance_method, point_per_year, s_update, n_twin_threshold, output_message)
}

cpp_nanMatrix <- function(nrow, ncol) {
    .Call(`_macam_cpp_nanMatrix`, nrow, ncol)
}

